import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import type { FC, ReactNode } from 'react';

import './globals.css';
import { cn } from '@/src/shared/lib/utils';
import Footer from '@/src/widgets/footer/Footer';

import Header from '../widgets/header/Header';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-sans',
});

const ardeco = localFont({
  src: [
    {
      path: '../../public/fonts/Ardeco.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-title',
});

const snell = localFont({
  src: [
    {
      path: '../../public/fonts/SnellRoundhand.otf',
      weight: '400',
      style: 'normal',
    },
  ],
  variable: '--font-first-letter',
});

const RootLayout: FC<{ children: ReactNode }> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={cn(
          'min-h-screen bg-background antialiased flex flex-col text-[18px] leading-[22.3px] font-normal tracking-[-1.27px]',
          inter.variable,
          ardeco.variable,
          snell.variable,
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
};
export default RootLayout;
