const filters = [
  {
    id: 1,
    title: 'Коллекции',
    data: [
      { value: '1', title: 'Коллекция ONE' },
      { value: '2', title: 'Коллекция TWO' },
      { value: '3', title: 'Коллекция THREE' },
      { value: '4', title: 'Коллекция FOUR' },
    ],
  },
  {
    id: 2,
    title: 'Цвет',
    data: [
      { value: '1', title: 'Светлые', color: '#e0e0e0' },
      { value: '2', title: 'Тёмные', color: '#828282' },
      { value: '3', title: 'Чёрно-белые', color: '#000000' },
      { value: '4', title: 'Голубые', color: '#71b2e1' },
      { value: '5', title: 'Жёлтые', color: '#f9d849' },
      { value: '6', title: 'Зелёные', color: '#59ae3f' },
      { value: '7', title: 'Красные', color: '#eb5757' },
      { value: '8', title: 'Оранжевые', color: '#ee8e48' },
      { value: '9', title: 'Серебряные', color: '#d0d0d0' },
      { value: '10', title: 'Синие', color: '#587edf' },
      { value: '11', title: 'Фиолетовые', color: '#9982d0' },
    ],
  },
  {
    id: 3,
    title: 'Металлизированные цвета',
    data: [
      { value: '1', title: 'Золото', color: '#d29c34' },
      { value: '2', title: 'Серебро', color: '#d0d0d0' },
      { value: '3', title: 'Бронза', color: '#b59775' },
    ],
  },
  {
    id: 4,
    title: 'Тип помещения',
    data: [
      { value: '1', title: 'Ванная' },
      { value: '2', title: 'Гостинная' },
      { value: '3', title: 'Детская' },
      { value: '4', title: 'Кабинет' },
      { value: '5', title: 'Кухня' },
      { value: '6', title: 'На потолок' },
      { value: '7', title: 'Прихожая' },
      { value: '8', title: 'Спальня' },
    ],
  },
  {
    id: 5,
    title: 'Стиль',
    data: [
      { value: '1', title: '3D' },
      { value: '2', title: 'Абстракция' },
      { value: '3', title: 'Ар-деко (современное)' },
      { value: '4', title: 'Арт' },
      { value: '5', title: 'Геометрия' },
      { value: '6', title: 'Графика' },
      { value: '7', title: 'Китайские' },
      { value: '8', title: 'Классика' },
      { value: '9', title: 'Лофт' },
      { value: '10', title: 'Минимализм' },
      { value: '11', title: 'Прованс' },
      { value: '12', title: 'Современные' },
      { value: '13', title: 'Шинуазри' },
      { value: '14', title: 'Японский' },
    ],
  },
  {
    id: 6,
    title: 'Сюжет',
    data: [
      { value: '1', title: 'Космос' },
      { value: '2', title: 'Линии' },
      { value: '3', title: 'Перья' },
    ],
  },
  {
    id: 7,
    title: 'Природа',
    data: [
      { value: '1', title: 'Весна' },
      { value: '2', title: 'Вода' },
      { value: '3', title: 'Водопад' },
      { value: '4', title: 'Город' },
      { value: '5', title: 'Горы' },
      { value: '6', title: 'Джунгли' },
      { value: '7', title: 'Зеленые листья' },
      { value: '8', title: 'Лес' },
      { value: '9', title: 'Листья' },
      { value: '10', title: 'Листья пальмы' },
      { value: '11', title: 'Листья папортника' },
      { value: '12', title: 'Море' },
      { value: '13', title: 'Облака' },
      { value: '14', title: 'Пальмовые листья' },
      { value: '15', title: 'Пейзаж' },
      { value: '16', title: 'Сад' },
      { value: '17', title: 'Тропики' },
      { value: '18', title: 'Туман' },
      { value: '19', title: 'Туманный лес' },
      { value: '20', title: 'Цветы' },
    ],
  },
  {
    id: 8,
    title: 'Свойства',
    data: [
      { value: '1', title: 'Бесшовные' },
      { value: '2', title: 'На стену' },
      { value: '3', title: 'Флизелиновые' },
    ],
  },
  {
    id: 9,
    title: 'Животные',
    data: [
      { value: '1', title: 'Журавли' },
      { value: '2', title: 'Олень' },
      { value: '3', title: 'Птицы' },
      { value: '4', title: 'С живностью' },
      { value: '5', title: 'Фламинго' },
    ],
  },
  {
    id: 10,
    title: 'Детские',
    data: [
      { value: '1', title: 'Для девочек' },
      { value: '2', title: 'Для мальчиков' },
      { value: '3', title: 'Для подростка' },
    ],
  },
];

export default filters;
