const wallpapers = [
  {
    id: 'VR.0016-A',
    title: 'Природа на закате',
    collection: 'Коллекция ONE',
    color: '#E0E0E0',
    roomType: 'Ванная',
    style: 'Современный',
    subject: 'Природа',
    price: 1500,
    imageUrl: 'https://example.com/wallpaper1.jpg',
  },
  {
    id: '2',
    title: 'Городской ландшафт',
    collection: 'Коллекция Modern',
    color: '#828282',
    roomType: 'Кабинет',
    style: 'Лофт',
    subject: 'Города',
    price: 2200,
    imageUrl: 'https://example.com/wallpaper2.jpg',
  },
  {
    id: '3',
    title: 'Летний лес',
    collection: 'Коллекция TWO',
    color: '#FCFAF7',
    roomType: 'Гостиная',
    style: 'Скандинавский',
    subject: 'Природа',
    price: 1800,
    imageUrl: 'https://example.com/wallpaper3.jpg',
  },
  {
    id: '4',
    title: 'Морской пейзаж',
    collection: 'Коллекция ONE',
    color: '#FF5733',
    roomType: 'Спальня',
    style: 'Минимализм',
    subject: 'Морские пейзажи',
    price: 2500,
    imageUrl: 'https://example.com/wallpaper4.jpg',
  },
  {
    id: '5',
    title: 'Джунгли в ночи',
    collection: 'Коллекция Modern',
    color: '#4CAF50',
    roomType: 'Детская',
    style: 'Классический',
    subject: 'Животные',
    price: 2100,
    imageUrl: 'https://example.com/wallpaper5.jpg',
  },
  {
    id: '6',
    title: 'Горная панорама',
    collection: 'Коллекция TWO',
    color: '#FF5733',
    roomType: 'Кабинет',
    style: 'Лофт',
    subject: 'Горы',
    price: 2600,
    imageUrl: 'https://example.com/wallpaper6.jpg',
  },
  {
    id: '7',
    title: 'Цветы в поле',
    collection: 'Коллекция ONE',
    color: '#828282',
    roomType: 'Гостиная',
    style: 'Современный',
    subject: 'Природа',
    price: 1700,
    imageUrl: 'https://example.com/wallpaper7.jpg',
  },
  {
    id: '8',
    title: 'Рыбы в океане',
    collection: 'Коллекция Modern',
    color: '#E0E0E0',
    roomType: 'Ванная',
    style: 'Минимализм',
    subject: 'Рыбы',
    price: 2000,
    imageUrl: 'https://example.com/wallpaper8.jpg',
  },
  {
    id: '9',
    title: 'Флора и фауна',
    collection: 'Коллекция Modern',
    color: '#FCFAF7',
    roomType: 'Спальня',
    style: 'Классический',
    subject: 'Животные',
    price: 2300,
    imageUrl: 'https://example.com/wallpaper9.jpg',
  },
  {
    id: '10',
    title: 'Пейзаж в тумане',
    collection: 'Коллекция Modern',
    color: '#4CAF50',
    roomType: 'Детская',
    style: 'Скандинавский',
    subject: 'Горы',
    price: 1900,
    imageUrl: 'https://example.com/wallpaper10.jpg',
  },
];

export default wallpapers;
