const wallpapers = [
  {
    id: '0001-A',
    title: 'Розовый закат',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0001-S1',
    title: 'Розовый закат',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0001-G1',
    title: 'Цветы на ветру',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0002-A',
    title: 'Цветы на ветру',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0002-G1',
    title: 'Цветы на ветру',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0002-S1',
    title: 'Тропическое утро',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0003-A',
    title: 'Тропическое утро',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0003-G1',
    title: 'Тропическое утро',
    collections: 'Коллекция ONE',
    color: '8',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0003-S1',
    title: 'Тропическое утро',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0004-A',
    title: 'Шинуазри А Ля Классик',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0004-A',
    title: 'Шинуазри А Ля Классик',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0004-B',
    title: 'Шинуазри А Ля Классик',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0004-G1',
    title: 'Шинуазри А Ля Классик',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0004-S1',
    title: 'Волшебная лоза',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0005-A',
    title: 'Волшебная лоза',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0005-S1',
    title: 'Волшебная лоза',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0005-G1',
    title: 'Волшебная лоза',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0006-A',
    title: 'Дивный вид',
    collections: 'Коллекция ONE',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0006-B',
    title: 'Дивный вид',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0006-S1',
    title: 'Дивный вид',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0007-A',
    title: 'Воздушное настроение',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0007-S1',
    title: 'Воздушное настроение',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0007-S2',
    title: 'Воздушное настроение',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0008-A',
    title: 'Растительный джаз',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0008-S1',
    title: 'Растительный джаз',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0008-S2',
    title: 'Растительный джаз',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0009-A',
    title: 'Парящий цветок',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0009-B',
    title: 'Парящий цветок',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0009-G1',
    title: 'Парящий цветок',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0009-S1',
    title: 'Парящий цветок',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0010-G1',
    title: 'Тропический шелк',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0010-S1',
    title: 'Тропический шелк',
    collections: 'Коллекция ONE',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0011-A',
    title: 'Голдшелл',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0011-G1',
    title: 'Голдшелл',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0011-S1',
    title: 'Голдшелл',
    collections: 'Коллекция ONE',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0012-A',
    title: 'Морская',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0012-G1',
    title: 'Морская',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0012-S1',
    title: 'Морская',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0013-A',
    title: 'Террагон',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0013-B',
    title: 'Террагон',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0013-S1',
    title: 'Террагон',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0014-A',
    title: 'Геометрия полёта',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0014-G1',
    title: 'Геометрия полёта',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0014-S1',
    title: 'Геометрия полёта',
    collections: 'Коллекция ONE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0015-A',
    title: 'Мистическая флора',
    collections: 'Коллекция ONE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0015-G1',
    title: 'Мистическая флора',
    collections: 'Коллекция ONE',
    color: '6',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0015-S1',
    title: 'Мистическая флора',
    collections: 'Коллекция ONE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0016-A',
    title: 'Ванильные небеса',
    collections: 'Коллекция TWO',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0016-S1',
    title: 'Ванильные небеса',
    collections: 'Коллекция TWO',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0016-Br1',
    title: 'Ванильные небеса',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0016-B',
    title: 'Ванильные небеса',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0017-S1',
    title: 'Мелодия',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0017-G2',
    title: 'Мелодия',
    collections: 'Коллекция TWO',
    color: '3',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0017-Br1',
    title: 'Мелодия',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0017-G1',
    title: 'Мелодия',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0023-S1',
    title: 'Палм-Сити',
    collections: 'Коллекция TWO',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0023-S4',
    title: 'Палм-Сити',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0023-S2',
    title: 'Палм-Сити',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0023-Br1',
    title: 'Палм-Сити',
    collections: 'Коллекция TWO',
    color: '3',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0020-G1',
    title: 'Золотая жила',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0020-S1',
    title: 'Золотая жила',
    collections: 'Коллекция TWO',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0020-Br1',
    title: 'Золотая жила',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0026-S1',
    title: 'Кошки модерна',
    collections: 'Коллекция TWO',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0026-G1',
    title: 'Кошки модерна',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0026-S2',
    title: 'Кошки модерна',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0019-A',
    title: 'Амазония',
    collections: 'Коллекция TWO',
    color: '3',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0019-S2',
    title: 'Амазония',
    collections: 'Коллекция TWO',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0019-S1',
    title: 'Амазония',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0019-G1',
    title: 'Амазония',
    collections: 'Коллекция TWO',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0031-S1',
    title: 'Древоцвет',
    collections: 'Коллекция THREE',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0031-Br1',
    title: 'Древоцвет',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0031-A',
    title: 'Древоцвет',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0032-C',
    title: 'Прибрежные Травинки',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0032-S1',
    title: 'Прибрежные Травинки',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0032-A',
    title: 'Прибрежные Травинки',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0032-B',
    title: 'Прибрежные Травинки',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0034-G1',
    title: 'Летние бражники',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0034-Br1',
    title: 'Летние бражники',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0034-A',
    title: 'Летние бражники',
    collections: 'Коллекция THREE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0037-S2',
    title: 'Дуновение тростника',
    collections: 'Коллекция THREE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0037-Br1',
    title: 'Дуновение тростника',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0037-S1',
    title: 'Дуновение тростника',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0048-S1',
    title: 'Тропическая декорация',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0048-A',
    title: 'Тропическая декорация',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0048-S2',
    title: 'Тропическая декорация',
    collections: 'Коллекция THREE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0036-Br1',
    title: 'Шинуазри на серебре',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0036-S1',
    title: 'Шинуазри на серебре',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: '0036-Br2',
    title: 'Шинуазри на серебре',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0038-A',
    title: 'Лебеди',
    collections: 'Коллекция THREE',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0038-S1',
    title: 'Лебеди',
    collections: 'Коллекция THREE',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0038-Br1',
    title: 'Лебеди',
    collections: 'Коллекция THREE',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0046-S1',
    title: 'Каштан',
    collections: 'Коллекция FOUR',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0046-A',
    title: 'Каштан',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0046-Br1',
    title: 'Каштан',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0047-S1',
    title: 'Жемчужные веера',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0047-A',
    title: 'Жемчужные веера',
    collections: 'Коллекция FOUR',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0047-Br1',
    title: 'Жемчужные веера',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0049-S1',
    title: 'Мексиканская ночь',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0049-Br1',
    title: 'Мексиканская ночь',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0049-Br2',
    title: 'Мексиканская ночь',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 5650,
  },
  {
    id: 'VR.0051-B',
    title: 'Одуванчики',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0051-A',
    title: 'Одуванчики',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0051-S1',
    title: 'Одуванчики',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0056-A',
    title: 'Светлячки',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0056-B',
    title: 'Светлячки',
    collections: 'Коллекция FOUR',
    color: '11',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0056-C',
    title: 'Светлячки',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0056-G1',
    title: 'Светлячки',
    collections: 'Коллекция FOUR',
    color: '2',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0057-A',
    title: 'Лесная тишина',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0057-S1',
    title: 'Лесная тишина',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: '0057-S2',
    title: 'Лесная тишина',
    collections: 'Коллекция FOUR',
    color: '1',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
  {
    id: 'VR.0058-S1',
    title: 'Ночная роса',
    collections: 'Коллекция FOUR',
    color: '9',
    metallicColors: null,
    roomTypes: null,
    styles: null,
    subjects: null,
    nature: null,
    properties: null,
    animals: null,
    discount: 0,
    children: null,
    price: 4290,
  },
];

export default wallpapers;
